version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      NODE_ENV: production
      WALLET: 49      # Example environment variable
      OPTION: 2       # Example environment variable
      OPTION_VALUE: 0.390378452  # Example environment variable
    ports:
      - "3007:3007"
    volumes:
      - ./shared:/usr/src/app/shared
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '2GB'
